name: Build Mroonga with MariaDB main
on:
  push:
    paths:
      - "**/*.cpp"
      - "**/*.h"
      - "**/*.hpp"
      - "**/CMakeLists.txt"
      - "**/Makefile.am"
      - ".github/workflows/linux.yml"
      - "configure.ac"
      - "doc/**"
      - "mysql-test/**"
      - "packages/**"
      - "version_*"
  pull_request:
    paths:
      - "**/*.cpp"
      - "**/*.h"
      - "**/*.hpp"
      - "**/CMakeLists.txt"
      - "**/Makefile.am"
      - ".github/workflows/linux.yml"
      - "configure.ac"
      - "doc/**"
      - "mysql-test/**"
      - "packages/**"
      - "version_*"
  schedule:
    - cron: |
        0 0 * * *
concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    name: Build
    timeout-minutes: 30
    strategy:
      fail-fast: false
    env:
      APACHE_ARROW_REPOSITORY: ${{ github.workspace }}/apache-arrow
      GROONGA_REPOSITORY: ${{ github.workspace }}/groonga
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          path: groonga
          repository: groonga/groonga
          submodules: recursive
      - uses: actions/checkout@v4
        with:
          path: mariadb
          repository: MariaDB/server
          submodules: recursive
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
      - name: Install required packages
        run: |
          sudo apt install -y \
            build-essential \
            ninja-build
      - name: Build MariaDB main
        run: |
          mkdir build-mariadb
          cmake \
            -S mariadb \
            -B build-mariadb \
            -GNinja \
            -DCMAKE_INSTALL_PREFIX=/tmp/local
          cmake --build build-mariadb -j$(nproc)
          cmake --install build-mariadb
      - name: Build Groonga main
        run: |
          mkdir build-groonga
          cmake \
            -S groonga \
            -B build-groonga \
            --preset=release-default \
            -DCMAKE_INSTALL_PREFIX="/tmp/local"
          cmake --build build-groonga -j$(nproc)
          cmake --install build-groonga
      - name: Build Mroonga
        run: |
          mkdir build-mroonga
          PKG_CONFIG_PATH=/tmp/local/lib/pkgconfig cmake \
            -S mroonga \
            -B build-mroonga \
            --preset=release \
            -DCMAKE_INSTALL_PREFIX="/tmp/local" \
            -DMYSQL_SOURCE_DIR=mariadb \
            -DMYSQL_BUILD_DIR=build-mariadb \
            -DMYSQL_CONFIG=/tmp/local/bin/mariadb_config
          cmake --build build-mroonga -j$(nproc)
          cmake --install build-mroonga

