name: Windows
on:
  push:
    branches:
      - main
      - "maintenance/**"
    tags:
      - "*"
  pull_request:
    paths:
      - "**/*.cpp"
      - "**/*.def"
      - "**/*.h"
      - "**/*.hpp"
      - "**/CMakeLists.txt"
      - ".github/workflows/windows.yml"
      - "mysql-test/**"
      - "packages/source/**"
      - "version_*"
  schedule:
    - cron: |
        0 0 * * *
concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  package:
    name: Package
    strategy:
      fail-fast: false
      matrix:
        include:
          - mariadb-release: "10.4"
          - mariadb-release: "10.5"
          - mariadb-release: "10.6"
          - mariadb-release: "10.11"
          - mariadb-release: "10.11"
            use-main: "yes"
          - mariadb-release: "10.11"
            use-main: "yes"
            embed: "ON"
    env:
      PACKAGE_PLATFORM: "winx64"
      VC_ARCHITECTURE: "x64"
    runs-on: windows-2019
    steps:
      - name: Disable crash dialog
        run: |
          reg add "HKCU\SOFTWARE\Microsoft\Windows\Windows Error Reporting" `
            /v DontShowUI `
            /t REG_DWORD `
            /d 1 `
            /f
      - name: Use JST
        run: |
          Set-TimeZone -Id "Tokyo Standard Time"
      - uses: actions/setup-ruby@v1
      - name: Detect MariaDB version
        run: |
          $releasesResponse = `
            Invoke-WebRequest `
              -Uri "https://downloads.mariadb.org/rest-api/mariadb/${{ matrix.mariadb-release }}/" `
              -Verbose | `
              ConvertFrom-Json
          $latestRelease = (($releasesResponse.releases | `
                               Get-Member -MemberType NoteProperty).Name | `
                              Sort-Object -Property {[Version]$_})[-1]
          $mariaDBVersion = $latestRelease
          Write-Output "MARIADB_VERSION=${mariaDBVersion}" | `
            Out-File -FilePath ${Env:GITHUB_ENV} -Encoding utf8 -Append
      - name: Cache MariaDB archive
        uses: actions/cache@v3
        with:
          path: download/
          key: download-mariadb-${{ env.MARIADB_VERSION }}
      - name: Download MariaDB
        run: |
          $mariadbTarGz = "download\mariadb-${Env:MARIADB_VERSION}.tar.gz"
          if (-not(Test-Path -Path ${mariadbTarGz})) {
            New-Item download -ItemType Directory -Force
            Invoke-WebRequest `
              -Uri "https://downloads.mariadb.org/rest-api/mariadb/${Env:MARIADB_VERSION}/mariadb-${Env:MARIADB_VERSION}.tar.gz" `
              -OutFile ${mariadbTarGz} `
              -Verbose
          }
          ridk exec tar xzf "${mariadbTarGz}"
          Move-Item mariadb-${Env:MARIADB_VERSION} mariadb
          Remove-Item mariadb\storage\mroonga -Recurse -Force
      - uses: actions/checkout@v4
        with:
          path: mariadb/storage/mroonga
          submodules: recursive
      - name: Set environment variables
        run: |
          $mroongaVersion = "$(Get-Content mariadb\storage\mroonga\version_full)"
          $artifactName = "mariadb-${mariaDBVersion}-with-mroonga-${mroongaVersion}"
          if ("${{ matrix.use-main }}" -eq "yes") {
            $artifactName += "-with-groonga-main"
          }
          if ("${{ matrix.embed }}" -eq "ON") {
            $artifactName += "-embed"
          }
          $artifactName += "-${Env:PACKAGE_PLATFORM}"
          Write-Output "MROONGA_VERSION=${mroongaVersion}" | `
            Out-File -FilePath ${Env:GITHUB_ENV} -Encoding utf8 -Append
          Write-Output "ARTIFACT_NAME=${artifactName}" | `
            Out-File -FilePath ${Env:GITHUB_ENV} -Encoding utf8 -Append
      - uses: actions/cache@v3
        with:
          path: |
            ~\AppData\Roaming\ccache
          key: source-${{ env.MARIADB_VERSION }}-${{ env.VC_ARCHITECTURE }}-ccache-${{ hashFiles('mariadb/storage/mroonga/**.{cpp,hpp,h}') }}
          restore-keys: source-${{ env.MARIADB_VERSION }}-${{ env.VC_ARCHITECTURE }}-ccache-
      - name: Prepare ccache
        run: |
          choco install ccache
          ccache --show-stats --verbose
          Write-Output "CMAKE_C_COMPILER_LAUNCHER=ccache" | `
            Out-File -FilePath ${Env:GITHUB_ENV} -Encoding utf8 -Append
          Write-Output "CMAKE_CXX_COMPILER_LAUNCHER=ccache" | `
            Out-File -FilePath ${Env:GITHUB_ENV} -Encoding utf8 -Append
      - name: Prepare MariaDB
        run: |
          cd mariadb
          if ("${Env:MARIADB_VERSION}" -match "^10\.5|^10\.6|^10\.11") {
            ridk exec patch -p1 -i `
              storage\mroonga\packages\source\patches\mariadb-10.5.5-add-a-missing-export-symbol.diff
          }
          Copy-Item storage\mroonga\build\mroonga_windows.cmake cmake\build_configurations\
      - uses: actions/checkout@v4
        if: |
          matrix.use-main == 'yes'
        with:
          path: mariadb/extra/groonga
          repository: groonga/groonga
          submodules: recursive
      - name: Prepare Groonga
        run: |
          cd mariadb
          if ("${{ matrix.use-main }}" -eq "yes") {
            pushd extra\groonga\vendor
            ruby download_lz4.rb
            ruby download_mecab.rb
            ruby download_message_pack.rb
            ruby download_rapidjson.rb
            ruby download_xxhash.rb
            ruby download.rb zstd
            popd
          } else {
            Invoke-WebRequest `
              -Uri "https://packages.groonga.org/source/groonga/groonga-latest.zip" `
              -OutFile groonga-latest.zip
            Expand-Archive groonga-latest.zip .
            Remove-Item groonga-latest.zip
            Move-Item groonga-* extra\groonga
          }
          Remove-Item extra\groonga\test -Recurse -Force
      - uses: actions/checkout@v4
        # TODO: Remove " || true" when we release
        # groonga-normalizer-mysql 1.2.3.
        if: |
          matrix.use-main == 'yes' || true
        with:
          path: mariadb/extra/groonga-normalizer-mysql
          repository: groonga/groonga-normalizer-mysql
          submodules: recursive
      - name: Download groonga-normalizer-mysql latest
        # TODO: Remove " -Or $true" when we release
        # groonga-normalizer-mysql 1.2.3.
        if: |
          !(matrix.use-main == 'yes' || true)
        run: |
          cd mariadb
          Invoke-WebRequest `
            -Uri "https://packages.groonga.org/source/groonga-normalizer-mysql/groonga-normalizer-mysql-latest.zip" `
            -OutFile groonga-normalizer-mysql-latest.zip
          Expand-Archive groonga-normalizer-mysql-latest.zip .
          Remove-Item groonga-normalizer-mysql-latest.zip
          Move-Item `
            groonga-normalizer-mysql-* `
            extra\groonga-normalizer-mysql
      - name: Run CMake
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %VC_ARCHITECTURE% || exit /B
          cmake ^
            -S mariadb ^
            -B build ^
            -G "Ninja" ^
            -DBUILD_CONFIG=mroonga_windows ^
            -DCMAKE_INSTALL_PREFIX=install ^
            -DCONNECT_WITH_LIBXML2=OFF ^
            -DMRN_GROONGA_EMBED=${{ matrix.embed || 'OFF' }} ^
            -DMRN_GROONGA_NORMALIZER_MYSQL_EMBED=${{ matrix.embed || 'OFF' }} ^
            -DGRN_WITH_MRUBY=ON ^
            -DGRN_WITH_WINDOWS_BACK_TRACE=OFF || exit /B
      - name: Install
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %VC_ARCHITECTURE% || exit /B
          set CMAKE_BUILD_PARALLEL_LEVEL=%NUMBER_OF_PROCESSORS%
          cmake ^
            --build build ^
            --config RelWithDebInfo ^
            --target install ^
            --verbose || exit /B
          ccache --show-stats --verbose
      - name: Create package
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %VC_ARCHITECTURE% || exit /B
          set CMAKE_BUILD_PARALLEL_LEVEL=%NUMBER_OF_PROCESSORS%
          cmake ^
            --build build ^
            --config RelWithDebInfo ^
            --target package ^
            --verbose || exit /B
          ccache --show-stats --verbose
      - name: Prepare package
        run: |
          pushd build
          Expand-Archive `
            mariadb-${Env:MARIADB_VERSION}-${Env:PACKAGE_PLATFORM}.zip `
            .
          pushd mariadb-${Env:MARIADB_VERSION}-${Env:PACKAGE_PLATFORM}
          Remove-Item mysql-test -Recurse -Force
          popd
          Move-Item `
            mariadb-${Env:MARIADB_VERSION}-${Env:PACKAGE_PLATFORM} `
            ..\
          popd
          Compress-Archive `
            -Path mariadb-${Env:MARIADB_VERSION}-${Env:PACKAGE_PLATFORM} `
            -DestinationPath "${Env:ARTIFACT_NAME}.zip"

      # Artifact
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_NAME }}.zip

      # Release
      - name: Upload the artifact to release
        if: |
          matrix.use-main != 'yes' && startsWith(github.ref, 'refs/tags/')
        run: |
          gh release upload ${Env:GITHUB_REF_NAME} `
            "${Env:ARTIFACT_NAME}.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: |
          pushd install\mysql-test\plugin\mroonga\mroonga
          Remove-Item wrapper -Recurse -Force
          pushd storage
          Remove-Item alter_table -Recurse -Force
          Remove-Item auto_increment -Recurse -Force
          Remove-Item binlog -Recurse -Force
          Remove-Item check_table -Recurse -Force
          Remove-Item collation -Recurse -Force
          Remove-Item column -Recurse -Force
          Remove-Item create -Recurse -Force
          Remove-Item delete -Recurse -Force
          Remove-Item drop -Recurse -Force
          Remove-Item foreign_key -Recurse -Force
          Remove-Item function -Recurse -Force
          Remove-Item geometry -Recurse -Force
          Remove-Item index -Recurse -Force
          Remove-Item information_schema -Recurse -Force
          Remove-Item insert -Recurse -Force
          Remove-Item like -Recurse -Force
          Remove-Item lock_tables -Recurse -Force
          Remove-Item optimization -Recurse -Force
          Remove-Item r -Recurse -Force
          Remove-Item repair_table -Recurse -Force
          Remove-Item replace -Recurse -Force
          Remove-Item select -Recurse -Force
          Remove-Item status -Recurse -Force
          Remove-Item sub_query -Recurse -Force
          Remove-Item t -Recurse -Force
          Remove-Item update -Recurse -Force
          Remove-Item variable -Recurse -Force
          Remove-Item fulltext\boolean_mode -Recurse -Force
          Remove-Item fulltext\charset -Recurse -Force
          Remove-Item fulltext\groonga -Recurse -Force
          Remove-Item fulltext\insert -Recurse -Force
          Remove-Item fulltext\multiple_column_index -Recurse -Force
          Remove-Item fulltext\order -Recurse -Force
          Remove-Item fulltext\t\empty_query.test -Recurse -Force
          Remove-Item fulltext\t\found_rows.test -Recurse -Force
          Remove-Item fulltext\t\index_recreate.test -Recurse -Force
          Remove-Item fulltext\t\multiple_index.test -Recurse -Force
          Remove-Item fulltext\t\no_primary_key.test -Recurse -Force
          Remove-Item fulltext\t\not_match_against.test -Recurse -Force
          Remove-Item fulltext\t\or.test -Recurse -Force
          Remove-Item fulltext\r\empty_query.result -Recurse -Force
          Remove-Item fulltext\r\found_rows.result -Recurse -Force
          Remove-Item fulltext\r\index_recreate.result -Recurse -Force
          Remove-Item fulltext\r\multiple_index.result -Recurse -Force
          Remove-Item fulltext\r\no_primary_key.result -Recurse -Force
          Remove-Item fulltext\r\not_match_against.result -Recurse -Force
          Remove-Item fulltext\r\or.result -Recurse -Force
          popd
          popd
          cd install\mysql-test
          $suites = `
            Get-ChildItem -Recurse -Directory -Name t plugin\mroonga | `
              Split-Path -Parent | `
              % {$_.replace("\", "/")}
          perl mysql-test-run.pl `
            --force `
            --no-check-testcases `
            --parallel=${Env:NUMBER_OF_PROCESSORS} `
            --retry=3 `
            --suite=$($suites -join ",")

#      - name: "Test: reference count"
#        run: |
#          cd install\mysql-test
#          $suites = `
#            Get-ChildItem -Recurse -Directory -Name t plugin\mroonga | `
#              Split-Path -Parent | `
#              % {$_.replace("\", "/")}
#          perl mysql-test-run.pl `
#            --force `
#            --mysqld=--loose-plugin-mroonga-enable-reference-count=ON `
#            --no-check-testcases `
#            --parallel=${Env:NUMBER_OF_PROCESSORS} `
#            --retry=3 `
#            --suite=$($suites -join ",")
